In [1]:
import pandas as pd

In [2]:
data = pd.read_json("/home/alhouceine@ljnad.lajavaness.com/balance-ton-salaire-EDA/output/tweets.jsonlines", lines=True)

In [3]:
data

,id,text,created_at,geo,author_id,source
0,1581232367313727490,Mdr les gens a 7k il tweet pas la ?#BalanceTon...,2022-10-15 10:35:48+00:00,None,1267673173430079488,Twitter for Android
1,1581231751397281794,#BalanceTonSalaire : les internautes affichent...,2022-10-15 10:33:22+00:00,None,2329776873,Twitter for iPhone
2,1581230905418338304,ðŸ’° Bon plan immÃ©diat ðŸ’°\nPour lâ€™ouverture dâ€™un c...,2022-10-15 10:30:00+00:00,None,1467973383799386118,Twitter Web App
3,1581230784920182787,"Cela te met hors de toi, de savoir que ton bos...",2022-10-15 10:29:31+00:00,None,1579357873267785737,Twitter Web App
4,1581230766574665728,Dernier salaire qu'on m'a proposÃ© en France fi...,2022-10-15 10:29:27+00:00,None,2884682543,Twitter Web App
...,...,...,...,...,...,...
4331,1579764262498897922,@BreakingInfosJR Je gagne 1300â‚¬/net par mois e...,2022-10-11 09:22:05+00:00,None,720231431839072256,Twitter Web App
4332,1579763192628408321,@BreakingInfosJR #BalanceTonSalaire\n\nTouchan...,2022-10-11 09:17:50+00:00,None,1502126898360508426,Twitter Web App
4333,1579753784443830274,J'attends celui de @Olivier_Truchot par exempl...,2022-10-11 08:40:27+00:00,None,1409120724195889158,Twitter for Android
4334,1579753462283526144,@BreakingInfosJR #BalanceTonSalaire Je gagne 3...,2022-10-11 08:39:10+00:00,None,1336728575412740100,Twitter Web App
4335,1579753009034428419,Je lance #BalanceTonSalaire !\n\nJe gagne 1500...,2022-10-11 08:37:22+00:00,None,1409120724195889158,Twitter for Android